// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtaReplaceSimulator.Infrastructure.Persistence;

#nullable disable

namespace OtaReplaceSimulator.Infrastructure.Migrations
{
    [DbContext(typeof(SimulatorDbContext))]
    partial class SimulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtaReplaceSimulator.Domain.ExternalProperty", b =>
                {
                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("numeric(18,15)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("numeric(18,15)")
                        .HasColumnName("longitude");

                    b.Property<int?>("MinimumNights")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_nights");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Neighbourhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("neighbourhood");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("RoomType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("room_type");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_version");

                    b.HasKey("ExternalId");

                    b.ToTable("external_properties", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
